/**
 * ORT Rest API
 * ORT API
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Data received in ase of successfull login
 */
export interface ApiAccess {
  
   encodeToken?:string;

    roles_recette?: Array<string>;

    code?: string;

    userName?: string;

    email?:string;

    codeFHAgency?:string;

    cgu?:boolean;

}
