/**
 * ORT Rest API
 * ORT API
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Credentials sent by the client for authentication
 */
export interface LoginCredentials {
    email?: string;

    password?: string;

    newPassword?: string;

}
